import React, { useState, useEffect } from 'react';
import { SecurityAuditReport } from '../types/security';
import { generateAiReport } from '../services/api';
import { Printer, Download, Sparkles, X, Check, Loader2, ShieldCheck, ShieldAlert, FileText } from 'lucide-react';

interface ExecutiveReportModalProps {
  report: SecurityAuditReport;
  onClose: () => void;
}

export const ExecutiveReportModal: React.FC<ExecutiveReportModalProps> = ({
  report,
  onClose,
}) => {
  const [aiReportText, setAiReportText] = useState<string>(report.executiveSummary || '');
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  useEffect(() => {
    // Automatically generate AI risk synthesis if not yet present
    if (!report.executiveSummary || report.executiveSummary.length < 250) {
      handleGenerateAiReport();
    }
  }, [report.id]);

  const handleGenerateAiReport = async () => {
    setIsGeneratingAi(true);
    try {
      const summary = await generateAiReport(report);
      setAiReportText(summary);
    } catch (err) {
      console.error('Failed to generate AI executive report:', err);
    } finally {
      setIsGeneratingAi(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `aegisscan-audit-${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();

    setDownloadSuccess('JSON exported');
    setTimeout(() => setDownloadSuccess(null), 2000);
  };

  const handleDownloadMarkdown = () => {
    const mdContent = `# AegisScan Security Vulnerability & Audit Report
**Target**: ${report.target} (${report.targetType})
**Scan Timestamp**: ${report.timestamp}
**Security Grade**: ${report.scorecard.grade} (${report.scorecard.numericScore}/100)
**Findings**: ${report.scorecard.criticalCount} Critical | ${report.scorecard.highCount} High | ${report.scorecard.mediumCount} Medium | ${report.scorecard.lowCount} Low

---

## Executive Risk Assessment
${aiReportText}

---

## Detailed Vulnerability Register
${report.findings
  .map(
    (f, idx) => `
### ${idx + 1}. [${f.severity}] ${f.title}
- **CVSS Score**: ${f.cvssScore}
- **CWE**: ${f.cweId}
- **OWASP**: ${f.owaspCategory}
- **Description**: ${f.description}
- **Impact**: ${f.impact}
- **Observed Evidence**: \`${f.observedEvidence}\`
- **Recommended Remediation**: ${f.recommendedFix}
`
  )
  .join('\n')}

*Generated by AegisScan Security Auditor*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security-report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadSuccess('Markdown exported');
    setTimeout(() => setDownloadSuccess(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-sm overflow-y-auto">
      <div className="relative w-full max-w-4xl rounded-xl border border-slate-800 bg-slate-900 shadow-2xl overflow-hidden my-6">
        {/* Top Action Bar (No-Print) */}
        <div className="no-print flex flex-wrap items-center justify-between border-b border-slate-800 px-6 py-4 bg-slate-900/90 gap-3">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-blue-400" />
            <h2 className="text-base font-bold text-white tracking-tight">Executive Security Report</h2>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleGenerateAiReport}
              disabled={isGeneratingAi}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-xs text-slate-300 hover:border-slate-700 hover:text-white transition-colors"
            >
              {isGeneratingAi ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin text-blue-400" />
              ) : (
                <Sparkles className="h-3.5 w-3.5 text-blue-400" />
              )}
              <span>Regenerate AI Analysis</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-xs text-slate-300 hover:border-slate-700 hover:text-white transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Markdown</span>
            </button>

            <button
              onClick={handleDownloadJson}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-xs text-slate-300 hover:border-slate-700 hover:text-white transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              <span>JSON/SARIF</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-1.5 text-xs font-semibold text-white hover:bg-blue-500 transition-colors"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print / Save PDF</span>
            </button>

            <button
              onClick={onClose}
              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors ml-2"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {downloadSuccess && (
          <div className="no-print bg-emerald-950/60 border-b border-emerald-800/40 px-6 py-2 text-xs text-emerald-300 flex items-center gap-2">
            <Check className="h-3.5 w-3.5" />
            <span>{downloadSuccess} successfully.</span>
          </div>
        )}

        {/* Printable Document Canvas */}
        <div className="p-8 space-y-8 max-h-[80vh] overflow-y-auto bg-slate-950 print:bg-white print:text-black print:max-h-none print:overflow-visible">
          {/* Document Header */}
          <div className="border-b border-slate-800 print:border-slate-300 pb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <div className="text-xs uppercase font-mono tracking-wider text-blue-400 print:text-blue-700 font-semibold mb-1">
                Automated Security Vulnerability Assessment
              </div>
              <h1 className="text-2xl font-bold text-white print:text-black font-mono">
                {report.target}
              </h1>
              <div className="flex items-center gap-2 text-xs text-slate-400 print:text-slate-600 mt-1">
                <span>Audited: {new Date(report.timestamp).toLocaleString()}</span>
                <span>·</span>
                <span>Scan ID: {report.id}</span>
              </div>
            </div>

            <div className="flex items-center gap-4 border border-slate-800 print:border-slate-300 rounded-lg p-4 bg-slate-900/60 print:bg-slate-50">
              <div className="text-right">
                <span className="text-[11px] uppercase tracking-wider text-slate-400 print:text-slate-600 block">
                  Security Grade
                </span>
                <span className="text-xs font-mono text-slate-400 print:text-slate-600">
                  Score {report.scorecard.numericScore}/100
                </span>
              </div>
              <div className="text-4xl font-black font-mono text-blue-400 print:text-blue-800">
                {report.scorecard.grade}
              </div>
            </div>
          </div>

          {/* Vulnerability Counts Summary Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 print:gap-2">
            <div className="border border-slate-800 print:border-slate-300 rounded-lg p-3 bg-slate-900/40 print:bg-white">
              <span className="text-xs text-rose-400 font-medium">Critical</span>
              <div className="text-2xl font-bold font-mono text-white print:text-black tabular-nums">
                {report.scorecard.criticalCount}
              </div>
            </div>
            <div className="border border-slate-800 print:border-slate-300 rounded-lg p-3 bg-slate-900/40 print:bg-white">
              <span className="text-xs text-amber-400 font-medium">High</span>
              <div className="text-2xl font-bold font-mono text-white print:text-black tabular-nums">
                {report.scorecard.highCount}
              </div>
            </div>
            <div className="border border-slate-800 print:border-slate-300 rounded-lg p-3 bg-slate-900/40 print:bg-white">
              <span className="text-xs text-yellow-400 font-medium">Medium</span>
              <div className="text-2xl font-bold font-mono text-white print:text-black tabular-nums">
                {report.scorecard.mediumCount}
              </div>
            </div>
            <div className="border border-slate-800 print:border-slate-300 rounded-lg p-3 bg-slate-900/40 print:bg-white">
              <span className="text-xs text-blue-400 font-medium">Low & Info</span>
              <div className="text-2xl font-bold font-mono text-white print:text-black tabular-nums">
                {report.scorecard.lowCount + report.scorecard.infoCount}
              </div>
            </div>
          </div>

          {/* AI Executive Threat Synthesis */}
          <div className="border border-slate-800 print:border-slate-300 rounded-xl p-6 bg-slate-900/30 print:bg-slate-50 space-y-4 print-break-inside-avoid">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-blue-400 print:text-blue-700" />
              <h2 className="text-sm font-bold uppercase tracking-wider text-white print:text-black">
                Executive Threat Analysis & Remediation Strategy
              </h2>
            </div>

            {isGeneratingAi ? (
              <div className="py-6 flex items-center justify-center gap-2 text-xs text-slate-400">
                <Loader2 className="h-4 w-4 animate-spin text-blue-400" />
                <span>Synthesizing risk models and remediation priorities with Gemini...</span>
              </div>
            ) : (
              <div className="text-xs text-slate-300 print:text-slate-800 leading-relaxed space-y-3 whitespace-pre-wrap font-sans">
                {aiReportText}
              </div>
            )}
          </div>

          {/* Complete Findings Register */}
          <div className="space-y-4">
            <h2 className="text-sm font-bold uppercase tracking-wider text-white print:text-black border-b border-slate-800 print:border-slate-300 pb-2">
              Detailed Vulnerability Register ({report.findings.length} findings)
            </h2>

            <div className="space-y-4">
              {report.findings.map((finding, idx) => (
                <div
                  key={finding.id}
                  className="border border-slate-800 print:border-slate-300 rounded-lg p-4 bg-slate-900/20 print:bg-white print-break-inside-avoid space-y-2 text-xs"
                >
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-slate-400 print:text-slate-600 font-semibold">
                        #{idx + 1}
                      </span>
                      <span
                        className={`font-mono text-[11px] font-semibold px-2 py-0.5 rounded ${
                          finding.severity === 'CRITICAL'
                            ? 'bg-rose-950 text-rose-300 border border-rose-800/40 print:bg-rose-100 print:text-rose-900'
                            : finding.severity === 'HIGH'
                            ? 'bg-amber-950 text-amber-300 border border-amber-800/40 print:bg-amber-100 print:text-amber-900'
                            : 'bg-yellow-950 text-yellow-300 print:bg-yellow-100 print:text-yellow-900'
                        }`}
                      >
                        {finding.severity}
                      </span>
                      <span className="font-bold text-white print:text-black text-sm">
                        {finding.title}
                      </span>
                    </div>

                    <div className="font-mono text-slate-400 print:text-slate-600">
                      CVSS {finding.cvssScore.toFixed(1)} · {finding.cweId}
                    </div>
                  </div>

                  <p className="text-slate-300 print:text-slate-700 leading-relaxed">
                    {finding.description}
                  </p>

                  <div className="bg-slate-950 print:bg-slate-100 p-2.5 rounded font-mono text-[11px] text-slate-400 print:text-slate-800 overflow-x-auto">
                    Evidence: {finding.observedEvidence}
                  </div>

                  <div className="text-slate-300 print:text-slate-800">
                    <span className="font-semibold text-slate-200 print:text-slate-900">
                      Remediation:{' '}
                    </span>
                    {finding.recommendedFix}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="border-t border-slate-800 print:border-slate-300 pt-4 text-[11px] text-slate-500 print:text-slate-600 flex justify-between">
            <span>AegisScan Application Security Auditor</span>
            <span>Confidential Security Assessment</span>
          </div>
        </div>
      </div>
    </div>
  );
};
